name: CD - Deploy Pipeline

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: gcr.io

jobs:
  # --- CD STAGE: DEPLOY TO GKE ---
  deploy-to-gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_ZONE }}

      - name: Update Image Tags and Deploy
        run: |
          # Define a helper list of your services
          SERVICES=("order-service" "application-service" "patient-service")

          for SERVICE in "${SERVICES[@]}"; do
            echo "Processing $SERVICE..."
            
            # Use | as delimiter to avoid path conflicts
            FULL_IMAGE="${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/$SERVICE:${{ vars.version }}"
            
            sed -i "s|{{IMAGE_NAME}}|$FULL_IMAGE|g" $SERVICE/k8s/deployment.yml
            
            # Apply resources
            kubectl apply -f $SERVICE/k8s/deployment.yml
            kubectl apply -f $SERVICE/k8s/service.yml
            kubectl apply -f $SERVICE/k8s/ingress.yml
          done

      - name: Validate Deployment Status
        run: |
          echo "Waiting for rollouts to finish..."
          kubectl rollout status deployment/order-service --timeout=90s
          kubectl rollout status deployment/application-service --timeout=90s
          kubectl rollout status deployment/patient-service --timeout=90s
          
          echo "Final Pod Check:"
          kubectl get pods -l "app in (order-service, application-service, patient-service)"
